version: '3.8'

services:
  gateway-api:
    build: .
    container_name: code-executor-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: always
